theforeman/puppet-foreman_proxy

- .sync.yml
- manifests/config.pp
- spec/classes/foreman_proxy__config__spec.rb
- spec/lib/module_spec_helper.rb
- spec/spec_helper.rb
- templates/sudo.erb
- templates/sudo_augeas.erb
* Set the puppetrun sudo command to match the user specified using puppetrun_user parameter
* Only manage the sudo rules if both puppetca and puppetrun are enabled
This is a refactor of #101 
The spec tests fail on my desktop, could use second pair of eyes as it appears like it shouldn't be failing.
> Improved sudo management

- spec/spec_helper.rb
This was added in 10ee4ce39093abcaba964312aaf6ff580ca46b93, most likely as some debugging tool.
> Remove custom module path in spec_helper

- manifests/install.pp
- manifests/proxydns.pp
- spec/classes/foreman_proxy__proxydns__spec.rb
Third-party packages are frequently managed with other modules causing
duplicate resource errors.  This changes management of the *bmc
provider* and *nsupdate* packages to be "soft" with the
`ensure_packages()` function, similar to GH-92.
> Use `ensure_packages()` for third-party packages

- manifests/init.pp
Nightly tests failed as validate_string was being called on `undef`: http://ci.theforeman.org/job/systest_foreman/6181/tapTestReport/fb-install-foreman.bats.out-11/
> refs #9896 - only validate tftp_servername when set

- manifests/params.pp
- spec/classes/foreman_proxy__config__spec.rb
I'd like to see a 2.2.2 after this has been merged before Foreman 1.8 release.
> Fixes #10255 - syslinux 6.x also needs ldlinux.c32

- manifests/params.pp
- spec/classes/foreman_proxy__config__spec.rb
> refs #10255 - syslinux 6.x also needs libutil.c32

- metadata.json
I forgot it was from a very new (April '15) version, which is probably why we hadn't hit the kafo bug before.
> Fix min version of stdlib for validate_integer

- manifests/plugin/chef/params.pp
- manifests/plugin/salt/params.pp
The plugin params classes that rely on foreman_proxy parameters should
only include the foreman_proxy::params class rather than the top-level
foreman_proxy class.
Kafo loads the params classes to determine default parameter values on
startup and including foreman_proxy caused this pre-flight run of
Puppet to make actual changes to the system state of foreman_proxy,
using default configuration values.
---
This nearly drove me insane.  Every time I ran foreman-installer -v, it was apparently making changes, yet every time I checked the files before and after, they were identical!
> Only include params class, not top-level class in plugin params

- Gemfile
- spec/classes/foreman_proxy__config__spec.rb
also, pin to `~>1.1`, otherwise we'd need to set `puppetversion` ourselves again for older versions.
> fix tests with rspec-puppet-facts 1.1

- README.md
- manifests/config.pp
- manifests/init.pp
- manifests/params.pp
- spec/classes/foreman_proxy__config__spec.rb
- templates/dns.yml.erb
- templates/dns_nsupdate.yml.erb
- templates/dns_nsupdate_gss.yml.erb
Initial work to split the DNS config. Untested and it doesn't manage the settings files.
> Per-provider DNS configuartion files

- spec/classes/foreman_proxy__config__spec.rb
To match theforeman/puppet-tftp@863f7e1
> Fix expected TFTP roots in tests

- manifests/params.pp
Puppet will always create the certificate filenames as lowercase, even if your hostname has uppercase characters in it.
> Fixes #8389 - Force certificate names to lowercase

- manifests/params.pp
- metadata.json
With puppet 4 the vardir points to /opt/puppetlabs/puppet/cache which
results into the incorrect ssldir.
> Use the correct puppet ssldir

- README.md
- manifests/config.pp
- manifests/init.pp
- manifests/params.pp
- spec/classes/foreman_proxy__config__spec.rb
- templates/dhcp.yml.erb
- templates/dhcp_isc.yml.erb
Two parts - first is to split up the config files in the same way as DNS works, secondly to rename the dhcp_vendor parameter to dhcp_provider for consistency with other modules and the new config files.
> refs #11081 - add DHCP split config files support

- manifests/init.pp
- manifests/params.pp
- templates/dhcp.yml.erb
Add new variable in params dhcp_subnets
Use validate_re to do a basic check if the IP addresses/masks are numbers
Set dhcp_subnets accordingly via template dhcp.yml.erb
Fixes GH-109
> Add check for params dhcp_subnets

- CHANGELOG.md
- manifests/config.pp
- manifests/init.pp
- manifests/params.pp
- spec/classes/foreman_proxy__config__spec.rb
- templates/sudo.erb
- templates/sudo_augeas.erb
The smart proxy module is simply called 'puppet' and is used for
environment importing as well as Puppet runs, so this should make the
relationship clearer.
---
As we're doing a major version we could just change it and remove the support for the deprecated parameters, would that be preferable?
> Rename puppetrun/puppetrun_listen_on to puppet

- CHANGELOG.md
- README.md
- manifests/config.pp
- manifests/init.pp
- manifests/params.pp
- spec/classes/foreman_proxy__config__spec.rb
- templates/puppet.yml.erb
- templates/puppet_proxy_customrun.yml.erb
- templates/puppet_proxy_legacy.yml.erb
- templates/puppet_proxy_mcollective.yml.erb
- templates/puppet_proxy_puppet_api.yml.erb
- templates/puppet_proxy_puppetrun.yml.erb
- templates/puppet_proxy_salt.yml.erb
- templates/puppet_proxy_ssh.yml.erb
- templates/sudo.erb
- templates/sudo_augeas.erb
1.12 splits the Puppet module up into many config files per puppetrun
provider and per environment import provider. 1.11 users must set the
`puppet_split_config_files` parameter to false to keep the single
puppet.yml.
A `mcollective_user` parameter has been added to expose the setting that
was introduced in 1.9.0 and is now in puppet_proxy_mcollective.yml.
Contains the commit from #249 as it conflicted and was helpful in keeping order.
> Deploy split Puppet module configuration files

- CHANGELOG.md
- manifests/config.pp
- manifests/init.pp
- manifests/params.pp
- spec/classes/foreman_proxy__config__spec.rb
- templates/puppet.yml.erb
Unused by the smart proxy since 1.9.0.
Closes GH-250
> Remove puppet_cache_location parameter

- README.md
- manifests/config.pp
- manifests/init.pp
- manifests/params.pp
- metadata.json
- spec/classes/foreman_proxy__config__spec.rb
- templates/dhcp.yml.erb
- templates/dns.yml.erb
- templates/puppet.yml.erb
- templates/settings.yml.erb
- remove libvirt_backend parameter
- remove puppet_split_config_files parameter
- mark Fedora 24 supported instead of Fedora 21
- remove Debian 7 (wheezy) support
- remove Ubuntu 12.04 (precise) 
the changelog would also come in another PR here
> remove formerly deprecated parameters and code

- manifests/config.pp
- manifests/init.pp
- manifests/params.pp
- spec/classes/foreman_proxy__config__spec.rb
In puppet 4 AIO packaging, it's the `puppetserver` package that creates
a `puppet` user and group.
The `puppet-agent` package doesn't create the group and unless
`puppetserver` is also installed the ssl keys and certs are owned by
`root:root` and are not readable by the foreman proxy. (It's the
installation of `puppetserver` that chowns the ssldir to
`puppet:puppet`)
With this commit, the module ensures that the `puppet_group` group
exists even on puppet 4.  It also makes sure the ssl_key/cert/ca files
are group owned by the `puppet_group`
The change is hopefully quite conservative.  Only if both `$puppet` and
`$puppetca` are false will it have any effect.  By default, it also
only applies to puppet 4 and can be turned off completely by setting
`manage_puppet_group` to `false`.
Users who …
> Ensure the `puppet` group exists

- manifests/plugin/abrt.pp
- manifests/plugin/chef.pp
- manifests/plugin/dynflow.pp
- manifests/plugin/openscap.pp
- manifests/plugin/pulp.pp
- manifests/plugin/remote_execution/ssh.pp
- manifests/plugin/salt.pp
This reduces the amount of default help text and confusing options for
plugins.  This is especially confusing for 'enabled' as there are 2
options:
--[no-]enable-foreman-proxy-plugin-remote-execution-ssh
--foreman-proxy-plugin-remote-execution-ssh-enabled
The former REALLY enables the plugin puppet module, the latter
is only controlling The value in the .yml configuration which has a
sane default value. We should hide this, and some of the other
options like listen_on, group, etc which probably don't need
changing ever.
> fixes #15556 - move some params to advanced

- manifests/params.pp
- manifests/plugin/discovery/params.pp
This removes the dependencies on the external tftp and puppet params classes, porting in the code where relevant.
> Remove dependencies on external modules

- spec/classes/foreman_proxy__plugin__discovery_spec.rb
Required when testing under strict variables.
(Should fix the new test failures under Puppet 4.)
> Fix Discovery plugin test to define foreman_proxy::plugin_version

- manifests/params.pp
- spec/classes/foreman_proxy__config__spec.rb
The feature is turned off by default because I was worried about memory
consumption, but during testing period it turned out this is working well. I
suggest to turn on the feature now.
> Enable smart-proxy logs feature by default

- manifests/plugin/pulp/params.pp
Kafo loads params manifests independently of the main manifests to
determine parameter defaults, and also parse order may not permit using
foreman_proxy parameters directly.
---
Will fix nightly test failures running the installer with 79e36af:
<pre>
</pre>
> Use defaults from foreman_proxy::params in Pulp plugin params

- manifests/tftp.pp
- spec/classes/foreman_proxy__config__spec.rb
The exec that generates the grub2/grubx86.efi file in the TFTP root runs
as root, but the recursive file resource on tftp_dirs specifies the file
owner as foreman-proxy. This causes the owner and selowner properties to
change back on the second run.
Adding a file resource ensures the file ownership etc. is set on the
first run after the file is generated.
---
Should fix installer idempotency failures seen on EL7 and Ubuntu 14.04 nightly tests:
> Manage ownership/mode/SELinux context of generated grubx86.efi

- manifests/config.pp
- manifests/init.pp
- manifests/params.pp
- spec/classes/foreman_proxy__config__spec.rb
The primary use case for this is when managing DNS but not managing the deployment of the DNS server, the foreman proxy user needs to be a member of the bind group.
> Allow additional groups for the foreman-proxy user

- manifests/config.pp
- manifests/tftp.pp
- spec/classes/foreman_proxy__config__spec.rb
Only install the directories and pxe files if tftp_managed is true.
> Only install directories if tftp is managed

- manifests/plugin/remote_execution/ssh.pp
smart_proxy_remote_execution_core was removed in 1.13
and even before, it was already handled in packaging.
No need to repeat ourselves here.
Fixes #287
> Handle rex ssh dependencies in packaging

- manifests/plugin/dynflow.pp
- manifests/plugin/remote_execution/ssh.pp
- spec/classes/foreman_proxy__plugin__dynflow_spec.rb
We need to link the proxy settings dir to make sure the config
is loaded properly. Needs https://github.com/theforeman/foreman-packaging/pull/1321
to work properly, without it it has no effect.
> Fixes #16050 - link dynflow_core settings to proxy

- manifests/init.pp
- manifests/params.pp
Kafo + Puppet 3 is unhappy with these without a parser cache:
```
[ERROR 2016-10-12 13:19:30 verbose] Parameter foreman-proxy-groups invalid: [] is not a valid string
[ERROR 2016-10-12 13:19:30 verbose] Parameter foreman-proxy-dhcp-range invalid: false is not a valid string
```
> Add array doc for groups and fix value for dhcp_range

- .fixtures.yml
newer versions are not compatible with Ruby 1.8.7
> pin puppetlabs-mysql to 3.9.0 for tests (4.0-stable)

- manifests/plugin/pulp/params.pp
The foreman_proxy class doesn't always seem to be available and loaded in the installer, so this ends up being just "/environments" on a real install in Puppet 3.
> Use puppetdir from params

- .fixtures.yml
- Gemfile
- Rakefile
- manifests/init.pp
- manifests/plugin/abrt.pp
- manifests/plugin/ansible.pp
- manifests/plugin/chef.pp
- manifests/plugin/dhcp/infoblox.pp
- manifests/plugin/discovery.pp
- manifests/plugin/dns/infoblox.pp
- manifests/plugin/dns/powerdns.pp
- manifests/plugin/dynflow.pp
- manifests/plugin/monitoring.pp
- manifests/plugin/omaha.pp
- manifests/plugin/openscap.pp
- manifests/plugin/pulp.pp
- manifests/plugin/salt.pp
- spec/aliases/listen_on_spec.rb
- spec/static_fixtures/test_module/manifests/listen_on.pp
- types/listenon.pp
Supported since Kafo 1.0.0, it performs more precise validation of
parameter values and can later be moved to the parameter definitions
when the module is made Puppet 4-only.
---
The odd testing of the type alias matches how stdlib's doing it, but in future rspec-puppet versions will hopefully be possible directly.
> Change existing Kafo type definitions to Puppet 4 types

- manifests/tftp.pp
- spec/classes/foreman_proxy__config__spec.rb
Building from scratch creates unsigned file which does not load with
SecureBoot. This change rather copies it from /boot folder.
> Fixes #16705 - copy signed grubx64.efi from /boot

- manifests/init.pp
- spec/classes/foreman_proxy__proxydns__spec.rb
By default the module assumes that we run Foreman in a small /24 network. BIND server expects reverse zones to be setup per /24 network chunks so this makes it impossible with current settings to create reverse zone for say /23 network.
This change is allowing us to either stick with the default string value for a small network or use an array to create necessary configuration. And the nature of it is making it backwards compatible with existing modules to setup Foreman.
> Allow $dns_reverse to be a string or an array

- manifests/init.pp
- spec/classes/foreman_proxy__config__spec.rb
This commit adds checks for the dhcp/dns/realms providers so that they
have to be compliant with a certain regex in order to be accepted as
parameters.
---- 
I know the values can come from plugins, and we effectively have no way of validating that the value doesn't come from a plugin. My argument is that in that case, the providers that come from plugins should be added to this repo to add the validation. 
Otherwise if you install a new plugin that provides a provider you manage the configuration yourself. It's nothing new, we already do this with the BMC provider (it's validated prior to this PR)
I can see how people can get frustrated by having their entire installation (if the proxy fails, the installation fails) aborted for getting such a minor thing wrong.
> Fixes #17631 - Validate realms/puppetrun providers

- manifests/plugin/ansible.pp
- manifests/plugin/ansible/params.pp
- spec/classes/foreman_proxy__plugin__ansible_spec.rb
- templates/plugin/ansible.cfg.erb
If the ansible proxy plugin is installed, this will make sure that
ansible is installed on the proxy and configured to use the foreman
callback plugin.
> Configure ansible for ansible proxy plugin

- manifests/plugin/abrt.pp
- manifests/plugin/ansible.pp
- manifests/plugin/chef.pp
- manifests/plugin/dynflow.pp
- manifests/plugin/openscap.pp
- manifests/plugin/salt.pp
During the discussion with the reporter of the issue we discovered that some plugins mention the name which makes the description clearer so I'm sending a PR that unifies the enable parameter description. The ticket is now in kafo project but very likely will be moved or closed. Feel free to wait with merging until it's in right project.
> Fixes #16148 - unify plugins description

- manifests/config.pp
- manifests/init.pp
- manifests/params.pp
- spec/classes/foreman_proxy__config__spec.rb
This change is because the "puppet" bool is used to control two different actions (configure puppet module in the smart proxy and add content to sudoers or sudoers.d) and should be separated in certain circumstances:
* Company policy may not allow for non-hostsec people to modify sudoers or sudoers.d (or, another process already controls those contents).
* Augeas in Puppet 3 cannot handle the "!$Cmnd_Alias" option in sudoers. (Note: This is solved in Puppet 4)
I created $use_sudoers (which is **very** similar to $use_sudoers**d**) to tell the module whether or not it can touch /etc/sudoers. If you set both $use_sudoersd and $use_sudoers to true, then the module should touch sudoers.d (due to the if/else statement's order). If you set them both to false, the module will leave sudoers and …
> Adding $use_sudoers bool

- manifests/init.pp
- manifests/params.pp
- spec/classes/foreman_proxy__config__spec.rb
- templates/settings.yml.erb
Version 1.15 will have support for an array of interfaces, so begin
allowing these to be specified. For 1.14 compatibility, a single
interface in an array will be configured as a string (also the default
value and behaviour.)
> Allow bind_hosts to be an array of interfaces

- manifests/tftp.pp
- spec/classes/foreman_proxy__config__spec.rb
- templates/grub.cfg.erb
See http://projects.theforeman.org/issues/16654
> Fix PXEGrub2 with vanilia GRUB2

- manifests/plugin/ansible.pp
- spec/classes/foreman_proxy__plugin__ansible_spec.rb
This implements the same logic for Ansible that's already in the REX SSH
plugin.
Closes GH-286
> Fix notification of the dynflow service on Debian

- spec/aliases/listen_on_spec.rb
`Puppet.version.to_f` on Puppet 4.10.0 will evaluate to `4.1`, causing
test and behavioural changes when conditionals check that the version is
equal or greater than versions such as `4.3`.
Version comparisons that are vulnerable to this have been changed to use
Puppet's versioncmp implementation, while most others only check for
for major version boundaries which is safe.
> Use versioncmp to check Puppet version for 4.10.x compatibility

- .fixtures.yml
- manifests/init.pp
- manifests/plugin/abrt.pp
- manifests/plugin/ansible.pp
- manifests/plugin/chef.pp
- manifests/plugin/dhcp/infoblox.pp
- manifests/plugin/dns/infoblox.pp
- manifests/plugin/dns/powerdns.pp
- manifests/plugin/dynflow.pp
- manifests/plugin/monitoring.pp
- manifests/plugin/omaha.pp
- manifests/plugin/openscap.pp
- manifests/plugin/pulp.pp
- manifests/plugin/remote_execution/ssh.pp
- manifests/plugin/salt.pp
- manifests/tftp.pp
Two fixes to have the tests pass again. ~~~The linting will still fail with an exception and failures in the traiing_comma check until puppet-lint 2.2.1's released, due to https://github.com/rodjek/puppet-lint/issues/681.~~~
> Pin xinetd, fix puppet-lint 2.2 warnings

- .fixtures.yml
- manifests/config.pp
- manifests/feature.pp
- manifests/plugin/abrt.pp
- manifests/plugin/ansible.pp
- manifests/plugin/chef.pp
- manifests/plugin/discovery.pp
- manifests/plugin/dynflow.pp
- manifests/plugin/monitoring.pp
- manifests/plugin/omaha.pp
- manifests/plugin/openscap.pp
- manifests/plugin/salt.pp
- manifests/register.pp
- manifests/settings_file.pp
- metadata.json
- spec/classes/foreman_proxy__plugin__discovery_spec.rb
- spec/classes/foreman_proxy__register__spec.rb
- spec/defines/foreman_proxy_feature_spec.rb
- spec/defines/foreman_proxy_settings_file_spec.rb
- templates/test.yml.erb
Uses datacat to generate an array of enabled features across built-in
and plugin modules by passing the feature name to settings_file, or
using the foreman_proxy::feature type.
> Set foreman_smartproxy features for built-in and plugin modules

- manifests/plugin/dynflow.pp
- manifests/plugin/dynflow/params.pp
- spec/classes/foreman_proxy__plugin__dynflow_spec.rb
- templates/plugin/dynflow_core.yml.erb
This option was added in https://github.com/theforeman/smart_proxy_dynflow/commit/13f7dfe17de94b0bb1a0fecddec834e945eb468b
> Fixes - #19956 Set ssl_disabled_ciphers dynflow_core setting

- manifests/init.pp
- manifests/params.pp
- manifests/proxydhcp.pp
- spec/classes/foreman_proxy__proxydhcp__spec.rb
http://steronius.blogspot.co.uk/2015/10/dhcp-failover-on-rhel-7.html is worth reading if you would like.
Today the user would have to find their own way of replicating leases - I'm hoping in the future Foreman can create the leases on both proxies but that would require some changes to Core.
> Fixes #19760 - Adds support for failover DHCP

- spec/classes/foreman_proxy__proxydhcp__spec.rb
Since we don't need to specify range, we shouldn't. This stems from when dhcp_range had a default we needed to override.
> Simplify DHCP tests with range

- manifests/plugin/dynflow.pp
- manifests/plugin/dynflow/params.pp
- spec/classes/foreman_proxy__plugin__dynflow_spec.rb
The persisted sqlite is not suitable for large scale that
is being used by remote execution.
> Fixes #20721 - use in-memory sqlite in smart proxy dynflow

- manifests/tftp.pp
There were several packages referenced in grub_packages that were obsoleted in RHEL 7.4 by packages suffixed with "-x64".
shim -> shim-x64
grub-efi -> grub-efi-x64
grub-efi-modules -> grub-efi-x64-modules
Example:
```
Red Hat Enterprise Linux Server release 7.4 (Maipo)
Loaded plugins: priorities, product-id, ps, search-disabled-repos, subscription-manager
osc_repo                                                                                                                                                                             | 2.9 kB  00:00:00     
Package shim-0.9-2.el7.x86_64 is obsoleted by shim-x64-12-1.el7.x86_64 which is already installed
Package 1:grub2-efi-2.02-0.44.el7.x86_64 is obsoleted by 1:grub2-efi-x64-2.02-0.64.el7.x86_64 which is already installed
Package …
```
> Fix TFTP grub_packages for RHEL 7.4+

- manifests/init.pp
- manifests/params.pp
- manifests/tftp.pp
Seems Foreman (at least in 1.13) will replace grub2.cfg when "Build PXE Default" is invoked in web interface.  This allows the Puppet module to be told to not replace the file that is managed by Foreman.
> Add tftp_replace_grub2_cfg parameter to disable replace of grub2.cfg

- manifests/proxydns.pp
- spec/classes/foreman_proxy__proxydns__spec.rb
This uses local variables and drops the (ignored) soaip parameter for reverse zones. The tests are rewritten to use the local variables which results in faster tests. A testcase for inherited parameters still exists to ensure that continues working.
> Improve proxydns

- .fixtures.yml
- .travis.yml
- CHANGELOG.md
- Gemfile
- manifests/tftp.pp
- spec/classes/foreman_proxy__config__spec.rb
This is a backport of a789325fcb76b3687112a5aa1d4b50e174301960 for the 1.15 branch.
> Fix TFTP grub packages for EL 7.4+

- manifests/plugin/openscap/params.pp
We already ship our packages and we no longer support el6. We could drop the param completely, but I suppose that'd break class API.
> Fixes #20939 - stop enabling the openscap repo

- manifests/init.pp
- manifests/params.pp
- manifests/proxydhcp.pp
- spec/classes/foreman_proxy__proxydhcp__spec.rb
Backport of bde9c889a9bd2816df89483962852e37c5e39c29
> Refs #20683 - Set ACLs on dhcp

- manifests/tftp.pp
Stage[main]/Foreman_proxy::Tftp/Exec[build-grub2-efi-image]/returns: /usr/bin/grub2-mkimage: error: cannot open `/var/lib/tftpboot/grub2/grubx64.efi': No such file or directory
> Add require on tftp dirs for build-grub2-efi-image

- manifests/proxydhcp.pp
f291aa33fbb6cef2428fd55fd2a23e52622fca0d refactored this to use Puppet 4 types but a copy-paste error means we no longer check the correct values.
> Use the correct variables when checking

- manifests/proxydhcp.pp
- spec/classes/foreman_proxy__proxydhcp__spec.rb
Due to the onlyif this was never executed. There was also a typo in the /var/lib/dhcp path. By using a loop we can use a variable that prevents this mismatch.
Spotted by @lpramuk
> Fixes #21419 - Fix DHCP directory ACL

- manifests/config.pp
Even though we have a boolean for this, this makes the chance of a conflict smaller.
Closes GH-389
> Use ensure_resource for sudoers.d

- .travis.yml
This is mostly to test if it fixes the build. If it does, it should be handled through modulesync.
> Reduce PARALLEL_TEST_PROCESSORS to 8

- manifests/init.pp
- manifests/params.pp
- manifests/proxydhcp.pp
- spec/classes/foreman_proxy__proxydhcp__spec.rb
This change adds a new parameter foreman_proxy::dhcp_additional_interfaces which defaults to the empty array `[]`. The parameter's value must be an array of interface names (i.e. an array of strings). When set the managed DHCP server will listen for DHCP requests on these interfaces, in addition to the interface specified in foreman_proxy::dhcp_interface. No subnets will be provisioned for these additional DHCP listen interfaces.
Fixes GH-400.
> Add support for additional DHCP listen interfaces

- lib/puppet/functions/foreman_proxy/get_network_in_addr.rb
- manifests/proxydns.pp
- spec/functions/get_network_in_addr_spec.rb
The legacy puppet3 functions-api should be avoided.
This migrates the existing function and its test to the new api and uses it in the module.
> Use puppet4 functions-api

- README.md
- manifests/config.pp
- manifests/init.pp
- manifests/params.pp
- spec/classes/foreman_proxy__config__spec.rb
- templates/puppetca.yml.erb
- templates/realm.yml.erb
We can assume new installations. Users of older versions should read the
notes on compatibility.
> Use modern defaults and document compatibility

- .sync.yml
- .travis.yml
- manifests/plugin/discovery.pp
- manifests/remote_file.pp
- spec/acceptance/foreman_remote_file_spec.rb
- spec/classes/foreman_proxy__plugin__discovery_spec.rb
- spec/defines/foreman_proxy_remote_file_spec.rb
This can happen when tftp is set to false or unmanaged.
We move the remote_file define to this module since puppet-foreman no longer uses it itself. That will allow us to remove it there in a next major release.
> Fixes #22479 - Handle remote directory with undefined parent

- manifests/plugin/ansible.pp
The callback needs this. It's already a very common package to have, but
if there's a clean installation of Foreman without Pulp, it will not be
there and the callback will not run until this dependency is installed.
> Fixes #22845 - Install python-requests with Ansible

- Gemfile
Facterdb 0.5.1 has ArchLinux facts which lack the legacy facts we rely on. These facts are still available, but not in facterdb. We can't rely on the new networking facts yet because facter 2.x (used on Debian and Fedora without AIO) doesn't have them.
Longer term we should support both fact styles and remove this pin.
> Pin facterdb to 0.5.0

- manifests/plugin/ansible.pp
- spec/classes/foreman_proxy__plugin__ansible_spec.rb
Currently we just mention it in the documentation https://github.com/theforeman/theforeman.org/pull/1033/files
but the installer should do this. The directory is used for some Ansible
tmp files
> Fixes #22842 - Create .ansible.cfg in /etc/foreman-proxy

- manifests/params.pp
- spec/classes/foreman_proxy__config__spec.rb
On Ruby 2.0 listening on * only listens on IPv4. Listening on :: listens on both IPv4 and IPv6.
Original issue:
https://bugs.ruby-lang.org/issues/7100
https://github.com/ruby/ruby/commit/b1f493dcd1092fe17cccec998e175516ed5c6e47
This will need a proper verification but I think we're seeing this issue in our CI pipeline where we set `/etc/hosts` with IPv6.
> Listen on IPv6 on EL7

- templates/puppet_proxy_puppetrun.yml.erb
Changes must be made in the sudo file, not in the YAML file where the
instructions are found.
I think  "'," at end of line is not required.
As puppetrun was in Puppet 2.7 and puppet kick is not supported
in Puppet 4, lets only mention Puppet 3 example here.
> Fix the instructions for puppet kick

- manifests/plugin/ansible/params.pp
- spec/classes/foreman_proxy__plugin__ansible_spec.rb
Using /etc/ansible means that the ~foreman-proxy/.ansible.cfg file we
had set up will be ignored. This means the callback is ignored and any
other options we might set in /etc/foreman-proxy/ansible.cfg
To reproduce, you can just start a centos7-katello-nightly box, install foreman-ansible and try to run a job. You'll run into the host key verification problem we try to solve in https://github.com/theforeman/foreman_ansible/pull/176 - even with `host_key_checking = False` in `/etc/foreman-proxy/ansible.cfg`
> Fixes #23905 - Use /usr/share/foreman-proxy as ansible_dir

- README.md
- manifests/config.pp
- manifests/init.pp
- manifests/params.pp
- spec/classes/foreman_proxy__config__spec.rb
- templates/puppetca.yml.erb
- templates/puppetca_hostname_whitelisting.yml.erb
This adds the settings for the `puppetca_hostname_whitelisting` provider for the new modular PuppetCa module. This should fix the current nightlies.
This is a part of #433 but without the `token_whitelisting` provider's settings and with the suggested additions.
This is a working copy of #434 because I sometimes am unable to work with git properly. See [previous commit](https://github.com/theforeman/puppet-foreman_proxy/pull/434/commits/3962a68e7987cc6a8455e34b9309daa27dc44fff).
> Refs #24012 - Add PuppetCA providers settings

- manifests/tftp.pp
Tests are giving me some weird errors locally about incorrect parameters, trying blindly.
> Fixes #24155 - explicitly set owner and permissions

- manifests/plugin/remote_execution/ssh/params.pp
- spec/classes/foreman_proxy__plugin__remote_execution__ssh_spec.rb
Starting 0.2.0-2 for Debs and 1.5.2 for RPMs we've moved the .ssh directory to /var/lib/foreman-proxy/ssh with a symlink in /usr/share/foreman-proxy/.ssh.
Depends on https://github.com/theforeman/foreman-packaging/pull/2891
> Move the REX SSH directory to /var/lib/foreman-proxy

- .fixtures.yml
- CHANGELOG.md
I created a 8.0-stable branch to avoid 69bf82aaab938dd88a86c0241a0fbc2a6253feef in 1.19 for now. It's probably going to be a breaking change for users.
> Release 8.0.1

- manifests/config.pp
- manifests/init.pp
- manifests/params.pp
- spec/classes/foreman_proxy__config__spec.rb
- templates/puppetca_token_whitelisting.yml.erb
As we are adding new providers to the PuppetCa SmartProxy module, we need to add its settings-file to the puppet module and add the settings as params to have them configurable.
See [SmartProxy-Refactor](https://github.com/theforeman/smart-proxy/pull/586) and new TokenWhitelistingProvider (to be pull-requested after refactor gets merged).
Waiting for both of the SmartProxy-PRs to get merged before removing WIP-status.
> Fixes #24012 - Add PuppetCA providers settings

- manifests/plugin/dhcp/infoblox.pp
- manifests/plugin/dhcp/infoblox/params.pp
- spec/classes/foreman_proxy__plugin__dhcp__infoblox_spec.rb
- templates/plugin/dhcp_infoblox.yml.erb
These are supported since smart_proxy_dhcp_infoblox 0.0.8. The defaults are copied from what the plugin uses and makes the implementation easier.
Closes GH-431
> Add {dns,network}_view parameters to infoblox

- metadata.json
This is in preparation for the 10.0.0 release that's currently master. See https://github.com/theforeman/puppet-puppet/pull/641 as well.
> Mark compatible with theforeman/puppet 10.x

- manifests/plugin/realm/ad.pp
This will instead discover the DC using an SRV record lookup in (r)adcli.
Requires theforeman/smart_proxy_realm_ad_plugin#19 on the proxy side
> realm_ad: Allow using unspecified DC

- manifests/init.pp
- manifests/params.pp
- templates/bmc.yml.erb
This commit adds support for the SSH BMC provider and all configuration options that come with it. Defaults have been copied from the official foreman docs.
> Add support for SSH BMC provider

- manifests/plugin/dhcp/infoblox.pp
- spec/classes/foreman_proxy__plugin__dhcp__infoblox_spec.rb
- templates/plugin/dhcp_infoblox.yml.erb
This parameter was removed in smart_proxy_dhcp_infobox 0.0.12.
> Fixes #25591 - Remove $use_ranges from infoblox dhcp

- manifests/init.pp
- manifests/install.pp
- manifests/params.pp
- spec/acceptance/basic_spec.rb
- spec/acceptance/http_spec.rb
- spec/classes/foreman_proxy__spec.rb
Because we're trying to move people away from the latest repository, we
set it to configure an explicit version with a default. Because this
default would need to be updated all the time, it's a bad idea.
This patch removes the $custom_repo and makes $repo undef by default.
This means users get no repository by default and need to explicitly
choose which repository to use.
Because repo management would not be of much interest to installer
users, we move it together with $gpgcheck to the advanced section.
> Disable repository management by default

- manifests/params.pp
This is likely incorrect. We also have the type as an Optional[String] but there's no way to unset the default. This forces a user to pick a gateway if they have one.
> Remove the default gateway

- manifests/plugin/ansible.pp
- manifests/plugin/ansible/params.pp
- spec/classes/foreman_proxy__plugin__ansible_spec.rb
- templates/plugin/ansible.cfg.erb
> Configure ansible's stdout_callback to yaml for nicer output

- metadata.json
Because of the minimum extlib version the older versions were effectively uninstallable, even if they were API compatible. It's also unlikely anyone tested those combinations.
Fixes GH-482
> Raise minimum foreman and puppet versions

- .fixtures.yml
- README.md
- manifests/plugin/remote_execution/ssh_user.pp
- manifests/plugin/remote_execution/ssh_user/params.pp
- spec/classes/foreman_proxy__plugin__remote_execution__ssh_user_spec.rb
- spec/spec_helper.rb
Especially useful if you have...
* Hosts that were built before you discovered/enabled remote execution
* You rebuild your foreman proxy server and the ssh keys are regenerated
> remote_execution ssh_user management

- manifests/config.pp
- manifests/init.pp
- manifests/params.pp
- spec/classes/foreman_proxy__register__spec.rb
- spec/classes/foreman_proxy__spec.rb
- templates/httpboot.yml.erb
This adds support for the httpboot module that's shipped since 1.20.  It's added under advanced since the default value is derived from whether tftp is enabled, but can be explicitly enabled. Its root dir is also hardcoded to the tftp directory.
> Fixes #25590 - Add httpboot support

- manifests/config.pp
- manifests/proxydns.pp
- spec/classes/foreman_proxy__spec.rb
The puppet group isn't as relevant anymore in various cases. This PR aims to make it fully optional.
> Fixes #26330 - Conditionally handle the puppet group

- templates/puppet_proxy_mcollective.yml.erb
The AIO package install puppet in `/opt/puppetlabs`, not `/opt/puppet`.
While here, remove garbage at end of line.
> Fix path to mco in example

- manifests/init.pp
I'm struggling with putting in the info that it only makes sense with some providers. For that I want some actual Puppet code to enforce it so I've left it out. I may even want to default to false for these.
> Fixes #26388 - Clarify the managed parameter docs

- manifests/tftp/netboot.pp
- spec/classes/foreman_proxy__tftp_spec.rb
It appears that `shim.efi` which is copied from boot partition has 700 permissions by default. That does not work with TFTP server, so the change makes sure it has the correct owner and also permissions (read for others).
> Ensure shim permissions

- manifests/plugin/dns/infoblox.pp
- manifests/plugin/dns/infoblox/params.pp
- spec/classes/foreman_proxy__plugin__dns__infoblox_spec.rb
- templates/plugin/dns_infoblox.yml.erb
I am pushing without testing this as my `rake spec` fails about 90% of all tests. This is a new install, Ruby 2.6, `bundle install` did not work as it wanted to upgrade `beaker` gem which I upgraded and then all tests were failing.
> Fixes #26839 - added dns_view option

- manifests/plugin/ansible.pp
This empty line breaks puppet-strings parsing which only looks at the comment block right above the class. puppet-lint-param-docs is more flexible in what it accepts so didn't catch it.
> Refs #27196 - Remote empty line

- manifests/plugin/dynflow.pp
- manifests/plugin/dynflow/params.pp
- spec/classes/foreman_proxy__plugin__dynflow_spec.rb
- templates/plugin/dynflow.yml.erb
this option is being introduced in https://github.com/theforeman/smart_proxy_dynflow/pull/63
> Add support for external Dynflow core 

- manifests/plugin/ansible.pp
- manifests/plugin/ansible/params.pp
- spec/classes/foreman_proxy__plugin__ansible_spec.rb
- templates/plugin/ansible.cfg.erb
In case of IPA there's a ProxyCommand set that handles known hosts, but `foreman_ansible` has its own way of handling known hosts. This sets the ssh args to force override this.
> Fixes #25481 - Set ProxyCommand=none for Ansible

- manifests/plugin/ansible.pp
- manifests/plugin/ansible/params.pp
- manifests/plugin/ansible/runner.pp
- spec/classes/foreman_proxy__plugin__ansible_spec.rb
As ansible-runner is going to be default way to run ansible, it should become a dependency at install time.
> Fixes #27264 - Install ansible-runner package

- spec/classes/foreman_proxy__spec.rb
- templates/puppet.yml.erb
Release 12.0.0 erroneously removed the :puppet_version setting from the
configuration file managing the "puppet" feature, preventing
foreman-proxy from starting up correctly.
Fixes GH-527
> Re-add :puppet_version setting to puppet.yml

- examples/journald.pp
- manifests/install.pp
- spec/acceptance/journald_spec.rb
- spec/classes/foreman_proxy__spec.rb
fde8d9b9547b1dc50b6010616b4aaf5bde51fbf4 attempted to implement installing foreman-proxy-journald when the logging was set to JOURNAL.  The check was comparing JOURNAL to JOURNALD.
This patch corrects it and adds both unit and acceptance tests.
> Fixes #27552 - Fix journald logging

- spec/classes/foreman_proxy__plugin__pulp_spec.rb
- templates/plugin/pulp3.yml.erb
This was included in the sample config, but wasn't actually read by the
pulp3 plugin. It should remain as a class parameter for the other config
files.
> Remove unused setting from pulp3

- manifests/params.pp
- spec/classes/foreman_proxy__plugin__pulp_spec.rb
- spec/classes/foreman_proxy__spec.rb
Not all machines have an IPv4 address. The datatype is `Optional[String]` so this is valid.
> Gracefully handle a missing IP address

- .sync.yml
- Gemfile
- manifests/params.pp
- spec/classes/foreman_proxy__spec.rb
- spec/classes/foreman_proxy__tftp__netboot_spec.rb
- spec/classes/foreman_proxy__tftp_spec.rb
7dff714 More robust check for IPv6
rspec-puppet 2.7.8 has started to always set an ipaddress6 fact and deleting no longer works. Setting it to nil does work. The fact() function returns a fact or undef if it can't be found which means it's still a valid way to check if IPv6 is present.
0c5514c Unpin facterdb
The latest version has ArchLinux facts with legacy facts.
> Fix tests by using a better IPv6 check

- README.md
- manifests/config.pp
- manifests/init.pp
- manifests/install.pp
- manifests/proxydns.pp
- spec/classes/foreman_proxy__proxydns__spec.rb
- spec/classes/foreman_proxy__spec.rb
When using any other provider than nsupdate, it doesn't make sense to include a managed bind and can only cause problems.
The nsupdate package manage is needed for nsupdate so moved to the installation part.
> Only manage DNS for the nsupdate provider

- manifests/config.pp
- spec/classes/foreman_proxy__spec.rb
The managed ISC DHCP server is only relevant when using the ISC provider, wether that's isc or remote_isc.
> Only manage ISC DHCP when using the ISC provider

- manifests/plugin/pulp.pp
- manifests/plugin/pulp/params.pp
- spec/classes/foreman_proxy__plugin__pulp_spec.rb
- templates/plugin/pulp3.yml.erb
This matches the pulp3.yml.example file with defaults that match the theforeman-pulpcore defaults.
> Add Pulp 3 HTTP URLs

- manifests/params.pp
- metadata.json
- spec/classes/foreman_proxy__plugin__discovery_spec.rb
- spec/classes/foreman_proxy__plugin__dynflow_spec.rb
- spec/classes/foreman_proxy__proxydhcp__spec.rb
- spec/classes/foreman_proxy__proxydns__spec.rb
- spec/classes/foreman_proxy__spec.rb
- spec/classes/foreman_proxy__tftp_spec.rb
- spec/defines/foreman_proxy_plugin_spec.rb
The package in AUR is version 1.13.0 and not supported by the module. The facts are also often causing failures.
Also cleans up the tests a bit to make sure they pass.
> Drop Archlinux support

- manifests/plugin/ansible/params.pp
- spec/classes/foreman_proxy__plugin__ansible_spec.rb
Based on https://docs.ansible.com/ansible/latest/reference_appendices/config.html#ansible-ssh-args
the ssh args is by default se to "-C -o ControlMaster=auto -o ControlPersist=60s". In #25481, this
was overriden to "-o ProxyCommand=none" only. There seems to be no way to just append areguments,
so listing defaults here is probably the best option.
> Fixes #28559 - keep default ssh args

- manifests/plugin/ansible.pp
- manifests/plugin/ansible/params.pp
Kafo is limited to trivial variables and literal strings so the array gets interpreted as a literal string which is not a valid path.
> Revert parameter simplification for Ansible plugin

- .fixtures.yml
- manifests/plugin/pulp.pp
- manifests/plugin/pulp/params.pp
- templates/plugin/pulp.yml.erb
- templates/plugin/pulpnode.yml.erb
This change removes the default value and looks it up at runtime. The benefit is that we can use the lookup method to get the answer for the puppet module.
The main driver for this is that the puppet_environmentpath fact has become unreliable with Kafo due to more isolation.
Also includes a fix to make the tests pass again.
> Fixes #28877 - Dynamically determine Pulp Puppet dir

- metadata.json
fecf9c8b8bc3a50bdc0ace5e96840fae90c9d240 started to depend on parameters only present in 7.0.0, but was merged before it could be added.
> Refs #29005 - Require theforeman/dns 7.x

- README.md
This makes it clear that 13.x is Foreman Proxy 2.0 only.
> Update the compatibility matrix in the README

- spec/acceptance/foreman_remote_file_spec.rb
Using HTTPS broke under Puppet 6.14 due to certificates:
Error: Failed to initialize SSL: The CA certificates are missing from '/etc/puppetlabs/puppet/ssl/certs/ca.pem'
Error: Run `puppet agent -t`
Error: Request to https://codeload.github.com/theforeman/puppet-foreman/tar.gz/9.0.0 failed after 0.001 seconds: The CA certificates are missing from '/etc/puppetlabs/puppet/ssl/certs/ca.pem'
Wrapped exception:
The CA certificates are missing from '/etc/puppetlabs/puppet/ssl/certs/ca.pem'
Error: /Stage[main]/Main/Foreman_proxy::Remote_file[/var/tmp/test]/File[/var/tmp/test]/ensure: change from 'absent' to 'file' failed: Request to https://codeload.github.com/theforeman/puppet-foreman/tar.gz/9.0.0 failed after 0.001 seconds: The CA certificates are missing from …
> Use HTTP in remote_file acceptance test

- spec/defines/foreman_proxy_feature_spec.rb
- spec/defines/foreman_proxy_plugin_spec.rb
- spec/defines/foreman_proxy_settings_file_spec.rb
* 8c30480 Use shorter syntax
* 220e763 Remove all OS testing for f_p:feature since it contains no OS logic and doesn't need facts. Testing on every OS is wasting time.
> Clean up rspec testing

- lib/puppet/functions/foreman_proxy/get_network_in_addr.rb
- manifests/config.pp
- manifests/feature.pp
- manifests/install.pp
- manifests/params.pp
- manifests/plugin.pp
- manifests/plugin/ansible/params.pp
- manifests/plugin/discovery.pp
- manifests/plugin/dynflow/params.pp
- manifests/plugin/monitoring/icingadirector/params.pp
- manifests/proxydhcp.pp
- manifests/proxydns.pp
- manifests/register.pp
- manifests/remote_file.pp
- manifests/service.pp
- manifests/settings_file.pp
- manifests/tftp.pp
- manifests/tftp/netboot.pp
- manifests/tftp/netboot/params.pp
- types/listenon.pp
This doesn't convert all classes since the installer still relies on rdoc groups. However, not all classes are public and this converts what makes sense.
> Document classes using puppet-strings

- manifests/service.pp
The parameter hasstatus has defaulted to true since Puppet 2.7.0 and that's long been the minimum supported version.
The require is already ensured in init.pp.
> Remove redundant parameters

- manifests/config.pp
- manifests/globals.pp
- manifests/init.pp
- manifests/params.pp
- manifests/plugin.pp
- manifests/plugin/ansible.pp
- manifests/plugin/ansible/params.pp
- manifests/plugin/dynflow.pp
- manifests/plugin/monitoring/icingadirector/params.pp
- manifests/settings_file.pp
- spec/defines/foreman_proxy_plugin_spec.rb
- spec/defines/foreman_proxy_settings_file_spec.rb
This class is intended to allow overriding some parameters that basically never change. This makes the parameters of init.pp slightly easier to digest. It also allows testing of some modules by just including params without the entire foreman_proxy class. This makes tests faster but also more focused.
> Introduce foreman_proxy::globals

- manifests/plugin/abrt.pp
- manifests/plugin/chef.pp
- manifests/plugin/chef/params.pp
- manifests/plugin/monitoring.pp
- manifests/plugin/omaha.pp
- manifests/plugin/pulp.pp
- manifests/plugin/pulp/params.pp
- manifests/plugin/realm/ad.pp
- manifests/plugin/salt.pp
- manifests/plugin/salt/params.pp
- spec/classes/foreman_proxy__plugin__abrt_spec.rb
- spec/classes/foreman_proxy__plugin__monitoring_spec.rb
- spec/classes/foreman_proxy__plugin__omaha_spec.rb
- spec/classes/foreman_proxy__plugin__pulp_spec.rb
- spec/classes/foreman_proxy__plugin__realm__ad_spec.rb
- spec/classes/foreman_proxy__plugin__salt_spec.rb
Setting the group can be useful if other processes need to read the file, but for foreman-proxy this is not the case.
> Drop group parameter on plugins

- manifests/params.pp
- manifests/plugin/remote_execution/ssh.pp
Rather than redefining the package prefix, this introduces the variable in params.pp.
> Move Ruby package prefix to params

- manifests/plugin/ansible.pp
- manifests/plugin/dynflow.pp
- manifests/plugin/remote_execution/ssh.pp
- spec/classes/foreman_proxy__plugin__dynflow_spec.rb
Since 5bde9c79ca05a7d30fd7ec7a85a109220b4950df there is a variable that explicitly sets the external core. Rather than copying the logic, this reuses the variable.
This should make https://github.com/theforeman/puppet-foreman_proxy/pull/516 easier.
> Use $f_p::plugin::dynflow::external_core

- manifests/plugin/omaha.pp
- templates/plugin/omaha.yml.erb
The following PR adds support for flatcar linux on the omaha smart proxy:
https://github.com/theforeman/smart_proxy_omaha/pull/21
We should add this as an option to the puppet module too.
> add support for flatcar

- .sync.yml
- spec/spec_helper_acceptance.rb
With the SCL build of foreman-proxy, I believe this is no longer needed.
> Drop EPEL in acceptance tests

- .fixtures.yml
c57d7fc64f2fa5a506f8531e482b081491dc7ff0 and possible Foreman itself used this in the past, but is no longer needed.
> Drop unused MySQL module fixture

- examples/tftp.pp
- manifests/tftp.pp
- manifests/tftp/netboot.pp
- manifests/tftp/netboot/params.pp
- spec/acceptance/netboot_spec.rb
- spec/classes/foreman_proxy__tftp__netboot_spec.rb
This module doesn't support EL 6 or < EL 7.5. To verify it does work, an acceptance test is added.
Also explicitly passes in the tftp root since it makes it easier to follow the variable flow.
> Remove old Red Hat TFTP install methods

- manifests/tftp/netboot.pp
- spec/classes/foreman_proxy__tftp__netboot_spec.rb
More info in the ticket. I am unable to run tests locally it fails with missing random_password method. Doing a blind test change.
> Fixes #29690 - install shimx64.efi and shim.efi

- manifests/params.pp
- spec/classes/foreman_proxy__spec.rb
The old FreeBSD port `bind910` is no longer available. The `nsupdate` tool is also available in the `bind-tools` port, which should be preferred over the full BIND distribution (which is available as `bind916`).
> replace nsupdate dependency on FreeBSD

- manifests/plugin/remote_execution/ssh.pp
- spec/classes/foreman_proxy__plugin__remote_execution__ssh_spec.rb
On EL8 the keys get generated in RFC4716 format which doesn't play well with the version of net-ssh we currently ship.
> Fixes #30121 - Generate SSH keys in PEM format

- manifests/params.pp
- spec/classes/foreman_proxy__register__spec.rb
- spec/classes/foreman_proxy__spec.rb
Not all installations require TFTP. This is only needed when doing kickstart/preseed/... installations. Typically that's bare metal but can be used on virtual machines as well. Doing those kind of installations also requires DHCP so disabling it is not a huge extra step.
> Fixes #30198 - Disable TFTP by default

- examples/dns.pp
- manifests/proxydns.pp
- metadata.json
- spec/acceptance/dns_spec.rb
- spec/setup_acceptance_node.pp
dda99d908f38c3e752928a9a2d570280477d581c marked the module as compatible with theforeman/dns 8.x. However, 8.x was a breaking change and no longer automatically grants access to the rndc-key by default. This restores compatibility.
I haven't had a chance to actually test this myself, but pushing this so this can be verified.
> Fixes #30240 - compat with theforeman/dns 8.x

- manifests/config.pp
- manifests/init.pp
- manifests/params.pp
- templates/puppetca.yml.erb
Since module version 13 this module is Foreman 2.0+ which means we must always use split configs. That makes this parameter redundant.
> Drop puppetca_split_configs parameter

- manifests/params.pp
TFTP on RedHat family 8 (tested on CentOS 8) needs some more files copied to tftpboot directory to be able to run PXE installation (tested with CentOS 8 and Debian buster).
> Fix tftp on RedHat 8

- manifests/init.pp
- manifests/params.pp
- manifests/proxydns.pp
I chose an empty string in case the fact is absent because `upcase()` should be able to handle it. I think this is a valid use because loading default parameters from this module (as in foreman-installer) should not fail, particularly when that parameter should not be used when the relevant feature is disabled.
> don't fail on upcase() when domain fact is undefined

- files/grub.cfg
- spec/acceptance/netboot_spec.rb
This happened now the third time and it took us to figure it out. Our installer deploys a copy of "PXEGrub2 global default" template which is susppoed to be overwirten after Build PXE default is clicked. However we never keep it up to date and we are getting feedback that "sometimes" the default template does not work well as we change it over the releases.
This is the definitive solution to this - users are asked to click on the button before they attempt to boot unknown hosts. This solves the issue (the template does not work for UEFI HTTP booted hosts) and prevents from this in the future.
> Fixes #30072 - update grub default template

- manifests/proxydhcp.pp
- spec/classes/foreman_proxy__proxydhcp__spec.rb
The cause for this change is the correct chaining. Previously there was no guarantee when the ACL was applied. In practice it was often done as: File[/etc/dhcp] -> Exec[setfacl] -> File[/etc/dhcp/dhcpd.conf]
This meant the dhcpd.conf file didn't receive the ACL anyway. After chaining to Class['dhcp'] (to guarantee all files existed) it turns out that /etc/dhcp/dhcpd.conf would become executable. That resulted in idempotency problems.
The Proxy needs to read dhcpd.conf, but that's guaranteed to be mode 0644 by theforeman/dhcp. Only the DHCP dir itself can have mode 0750 (owned by root:root) which is why the ACL is needed. By making it non-recursive and done after Class[dhcp] these problems are avoided.
This is an alternative to https://github.com/theforeman/puppet-foreman_proxy/pull/620. …
> Do not set recursive ACLs on dhcp

- examples/isc_dhcp.pp
- examples/isc_dhcp_omapi.pp
- manifests/proxydhcp.pp
- spec/acceptance/isc_dhcp_spec.rb
- spec/classes/foreman_proxy__proxydhcp__spec.rb
The Proxy needs to read dhcpd.conf. Normally that's guaranteed to be mode 0644 by theforeman/dhcp. In case there is an omapi key, there is a secret that needs to be hidden (CVE-2020-14335). The previous patch relied on the recursive ACL and then setting the mode to 0640.
The cause for this change is the correct chaining. Previously there was no guarantee when the ACL was applied. In practice it was often done as: File[/etc/dhcp] -> Exec[setfacl] -> File[/etc/dhcp/dhcpd.conf]
This meant the dhcpd.conf file didn't receive the ACL. Since there was no group set, this means foreman-proxy couldn't read the DHCP config.  After chaining to Class['dhcp'] (to guarantee all files existed) it turns out that /etc/dhcp/dhcpd.conf would become executable. That resulted in idempotency problems.
Only the …
> Fixes #30962 - Correct DHCP file permissions

- manifests/proxydhcp.pp
- spec/classes/foreman_proxy__proxydhcp__spec.rb
By default this directory is set to mode 0755 on EL7, EL8, Debian 10 and Ubuntu 18.04. Those are all the platforms we set ACLs so there's no need to do this.
The result is that rpm -qV dhcp (on EL7) doesn't complain about /var/lib/dhcpd being modified.
> Do not set ACLs on DHCP leases directory

- README.md
- manifests/config.pp
- manifests/init.pp
- manifests/module/registration.pp
- manifests/params.pp
- spec/classes/foreman_proxy__register__spec.rb
- templates/registration.yml.erb
Waiting for: https://github.com/theforeman/smart-proxy/pull/768
---
PR is part of **Simple & automatic host registration WF**, see:
* [RFC](https://community.theforeman.org/t/rfc-simple-automatic-host-registration-wf/19588)
* [Redmine (this PR)](https://projects.theforeman.org/issues/30950)
* [Redmine (Parent task)](https://projects.theforeman.org/issues/30440)
> Fixes #30950 - Enable SmartProxy Registration module

- spec/acceptance/journald_spec.rb
This is broken on Docker CE. It worked in the past (and still does when using Docker in EL7). This should have been updated when it was migrated to Github Actions.
> Skip journal check on EL7 when using Docker

- manifests/init.pp
- manifests/params.pp
- spec/classes/foreman_proxy__spec.rb
- templates/dhcp.yml.erb
Foreman 1.24 introduced this option and it should be exposed so users can change it.
> Fixes #31415 - Expose DHCP's ping_free_ip option

- manifests/init.pp
- manifests/module/httpboot.pp
- manifests/params.pp
- spec/classes/foreman_proxy__spec.rb
Since Foreman Proxy 1.22 the hard requirement on TFTP is no longer present. This changes the default to always be off, rather than on. This makes sense since in the default deployment HTTP is off and most installations don't support booting over HTTPS.
To get the netboot files, the TFTP feature must still be enabled.
This is still a draft since I'm not sure if we should move the netboot file management to a higher level so you can run the HTTPBoot feature without the TFTP daemon.
> Fixes #30449 - Do not require TFTP for HTTPBoot

- manifests/plugin/container_gateway.pp
- spec/classes/foreman_proxy__plugin__container_gateway_spec.rb
- templates/plugin/container_gateway.yml.erb
Adds support for the Container Gateway smart proxy plugin.
I'm pretty new to the foreman-installer so let me know any places where I'm breaking standards.
TODO:
> Fixes #31642 - Add container gateway support

- README.md
- manifests/plugin/dynflow.pp
- manifests/plugin/dynflow/params.pp
- spec/acceptance/dynflow_spec.rb
- spec/classes/foreman_proxy__plugin__dynflow_spec.rb
Implements step 2 of [Phasing out smart_proxy_dynflow_core](https://community.theforeman.org/t/phasing-out-smart-proxy-dynflow-core/22841)
> Fixes #32235,#19494 - Run Dynflow within smart-proxy on EL*

- metadata.json
The backwards incompatible changes do not affect this module.
> Mark compatible with Foreman 17.x

- manifests/params.pp
We can now assume we're on Puppet 4 or newer and default to true.
> Remove Puppet version check

- manifests/plugin/pulp.pp
- manifests/plugin/pulp/params.pp
- spec/classes/foreman_proxy__plugin__pulp_spec.rb
- templates/plugin/pulp.yml.erb
- templates/plugin/pulpnode.yml.erb
Katello 4.0 drops Pulp 2 in favor of Pulp 3 completely. If this
plugin is used, then Pulpcore will be used and the user can decide
if it should be deployed as a mirror configuration or not. This drops
most of the parameters as they are not relevant with Pulp 3.
I was not sure if disabling the Pulp 2 plugins was all that needed doing. At some point we will want to clean them up but figured I'd start by just disabling them. This is obviously backwards incompatible. I prefer to have latest reflect the state of Katello 4.0 given its so different. We could resort to erroring out when a user attempts to use parameters that dont work with 4.0, but that also means we have to keep around a lot this parameter cruft for a lot longer period of time. Further, in the installers use case, this would …
> Update Pulp plugin to drop Pulp 2

- manifests/plugin/dns/route53.pp
- spec/classes/foreman_proxy__plugin__dns__route53_spec.rb
- templates/dns.yml.erb
- templates/plugin/dns_route53.yml.erb
Based heavily on the code for the powerdns plugin, I added support for the smart_proxy_dns_route53 plugin. Tested in our own dev and prod foreman deployments. I also added "dns_route53" to the list of valid providers in templates/dns.yml.erb and alphabetized the list.
> adding smart_proxy_dns_route53 plugin support

- metadata.json
This should have been included in the 18.0.0 release
of this module.
> Allow puppet-puppet < 16.0.0

- manifests/params.pp
- manifests/plugin/ansible/params.pp
- metadata.json
- spec/acceptance/netboot_spec.rb
- spec/classes/foreman_proxy__plugin__discovery_spec.rb
- spec/classes/foreman_proxy__spec.rb
- spec/classes/foreman_proxy__tftp_spec.rb
The most notable change is that Ubuntu 20.04 changes the tftp root from /var/lib/tftpboot to /srv/tftp. This matches Debian again.
The other change is that it ships a new enough Ansible to use the callback from collections.
Replaces https://github.com/theforeman/puppet-foreman_proxy/pull/666 & https://github.com/theforeman/puppet-foreman_proxy/pull/667.
> Support Ubuntu 20.04

- manifests/plugin/pulp.pp
- spec/classes/foreman_proxy__plugin__pulp_spec.rb
- templates/plugin/pulpcore.yml.erb
Depends on the outcome of https://github.com/theforeman/smart_proxy_pulp/pull/28
> Add client_authentication parameter to plugin::pulp 

- manifests/init.pp
- manifests/install.pp
- spec/classes/foreman_proxy__spec.rb
This prefers that the Foreman class repo is used. The benefit is that a user doesn't end up with effectively the same repository twice. Once named foreman and once foreman_proxy, but pointing to the same URL.
To keep the order consistent, it does collect the anchor that foreman::repo has which guarantees that the repo is set up before packages are installed.
> Remove Foreman repository parameters

- manifests/init.pp
- manifests/tftp/netboot.pp
- spec/classes/foreman_proxy__spec.rb
- spec/classes/foreman_proxy__tftp__netboot_spec.rb
The release of puppetlabs-stdlib included a change to ensure_packages
that defaults to installed rather than present. Additionally, if
ensure_packages provides an override set to present, this is internally
converted to installed. Thus any previous test that checked for present
fails.
This updates the tests to check for installed and updates the defaults
within the module from present to installed to match the default behavior
of ensure_packages.
Ref: https://github.com/puppetlabs/puppetlabs-stdlib/commit/842992eb834d72163f5d2dcf8fab8deef15225f9
> Default package versions to installed instead of present

- manifests/init.pp
In cf0da38cc900f3d927e4de9eed8f4fabc7c5bedc the parameters were changed and this unintentionally introduced a regression by changing the default from both to https.
Fixes: cf0da38cc900f3d927e4de9eed8f4fabc7c5bedc
> Fixes #33808: Make templates listen on both again

- manifests/plugin/ansible.pp
- manifests/plugin/ansible/params.pp
- manifests/plugin/reports.pp
- spec/classes/foreman_proxy__plugin__ansible_spec.rb
- spec/classes/foreman_proxy__plugin__reports_spec.rb
- templates/plugin/ansible.cfg.erb
- templates/plugin/reports.yml.erb
I've just noticed https://projects.theforeman.org/issues/33704...
> Refs #33760 - Add reports proxy plugin

- metadata.json
- spec/classes/foreman_proxy__plugin__discovery_spec.rb
- spec/classes/foreman_proxy__spec.rb
- spec/classes/foreman_proxy__tftp_spec.rb
Foreman 3.1 drops Ubuntu 18.04 support. This reflects that change.
> Drop Ubuntu 18.04 support

- spec/classes/foreman_proxy__plugin__salt_spec.rb
In order to increase the readability of the code, this PR replaces the backslashes in the Salt spec file.
> Salt spec replace backslash

- manifests/proxydhcp.pp
There's a race-condition in config.pp where the inclusion of
proxydhcp.pp can run setfacl before the user is created.
> setfacl needs foreman_proxy::user to exist

- manifests/init.pp
- manifests/proxydhcp.pp
- spec/classes/foreman_proxy__proxydhcp__spec.rb
Hey folks,
I have added a parameter `dhcp_ipxefilename` to set a iPXE boot file in the isc dhcp server. [fixes #703]
Thanks in advance
Harm
> Fixes #33549 - Add parameter dhcp_ipxefilename to set a value for DHCP's iPXE filename

- .fixtures.yml
- Gemfile
- manifests/init.pp
In cf0da38cc900f3d927e4de9eed8f4fabc7c5bedc the parameters were changed
and this unintentionally introduced a regression by changing the default
from both to https.
Fixes: cf0da38cc900f3d927e4de9eed8f4fabc7c5bedc
(cherry picked from commit 0d5afc55976bbdcde8a8941a337a6364778ec133)
> Fixes #33808 - Make templates listen on both again

- manifests/plugin/remote_execution/ssh.pp
- spec/classes/foreman_proxy__plugin__remote_execution__ssh_spec.rb
The package is not required since smart_proxy_remote_execution_ssh-0.5.0
and is no longer packaged in foreman repositories
> [REX SSH Plugin] Don't manage net-ssh-krb package

- manifests/config.pp
- manifests/globals.pp
- manifests/params.pp
- spec/classes/foreman_proxy__spec.rb
This provides auto requires, for example when you want to manage certificates in the config directory.
> Ensure the config directory, user and deal with a missing domain

- examples/remote_execution_ssh.pp
- spec/acceptance/remote_execution_ssh_spec.rb
Idempotency is currently broke due to a mismatch between Puppet and packaging: see https://github.com/theforeman/foreman-packaging/pull/7799
> Add acceptance tests for remote_execution::ssh

- manifests/globals.pp
- manifests/init.pp
- manifests/params.pp
- manifests/tftp.pp
- spec/classes/foreman_proxy__spec.rb
advanced users who might want to change this, can override this by
setting `foreman_proxy::globals::tftp_syslinux_filenames` in hiera
> Fixes #34774 - don't expose tftp syslinux files directly

- manifests/plugin/remote_execution/ssh.pp
To make the coding style of foreman_proxy::plugin::remote_execution::ssh
consistent with the other code in this module.
Related to #734
> add missing class param training comma

- .fixtures.yml
- examples/remote_execution_script_pull_mqtt.pp
- manifests/plugin/remote_execution/mosquitto.pp
- manifests/plugin/remote_execution/script.pp
- spec/acceptance/remote_execution_script_pull_mqtt_spec.rb
- templates/plugin/foreman.acl.epp
Builds on:
- https://github.com/theforeman/puppet-foreman_proxy/pull/736
- https://github.com/theforeman/puppet-foreman_proxy/pull/735
- https://github.com/theforeman/puppet-foreman_proxy/pull/734
> Fixes #34239: Add pull-mqtt support to smart_proxy_remote_execution

- manifests/init.pp
- manifests/install.pp
- spec/classes/foreman_proxy__spec.rb
- templates/bmc.yml.erb
This adds Redfish BMC support
The feature is not (yet) documented anywhere, but the smart proxy supports Redfish and it seems to work fine: https://github.com/theforeman/smart-proxy/blob/develop/modules/bmc/bmc_api.rb#L421
> Support BMC redfish integration

- spec/acceptance/ansible_spec.rb
- spec/acceptance/basic_spec.rb
- spec/acceptance/dns_spec.rb
- spec/acceptance/dual_spec.rb
- spec/acceptance/dynflow_spec.rb
- spec/acceptance/http_spec.rb
- spec/acceptance/journald_spec.rb
- spec/acceptance/netboot_spec.rb
- spec/acceptance/remote_execution_script_pull_mqtt_spec.rb
- spec/acceptance/remote_execution_script_spec.rb
- spec/support/acceptance/cleanup.rb
otherwise `remote_execution_script_pull_mqtt_spec.rb` leaves `mosquitto`
installed and `remote_execution_script_spec.rb` will encounter a system
where `/etc/mosquitto` exists
> correctly clean up mosquitto inbetween tests

- manifests/globals.pp
- manifests/params.pp
- spec/classes/foreman_proxy__spec.rb
To allow the login shell of the foreman-proxy user to be overridden.
On EL7, after the `smart_proxy_remote_execution_ssh` gem switched from `Net::SSH` to shelling out to run `ssh`, REX is completely broken for me with the `foreman-proxy` user's shell set to `/bin/false`.  Changing the shell to `/bin/bash` allows ssh to function.
> add foreman::shell param

- examples/discovery.pp
- manifests/plugin/discovery.pp
- spec/acceptance/discovery_spec.rb
- spec/classes/foreman_proxy__plugin__discovery_spec.rb
- templates/plugin/discovery.yml.erb
In our production environment, `/etc/foreman-proxy/settings.d` is purged of un-managed files.  This results in `/etc/foreman-proxy/settings.d/discovery.yml` being deleted and the discovery plugin becoming disabled.
> manage discovery plugin config file

- README.md
- manifests/plugin/ansible.pp
- manifests/plugin/ansible/runner.pp
- spec/classes/foreman_proxy__plugin__ansible_spec.rb
The ansible-runner package is now delivered via the Foreman plugins repository.
Requires that ansible-runner be in the plugins repository (https://github.com/theforeman/foreman-packaging/pull/8434)
> Drop ansible-runner repository management

- manifests/config.pp
- manifests/plugin/dns/infoblox.pp
- spec/classes/foreman_proxy__spec.rb
When the user specifies a known DNS provider, the plugin class should be included to manage it. This also means it becomes possible to simply `include foreman_proxy` and fully configure it via Hiera without additional includes.
> Automatically include plugin dns provider classes

- spec/classes/foreman_proxy__spec.rb
- templates/settings.yml.erb
This option is being removed from the Smart Proxy and should no longer be present.
It is likely to break BSD deployments which relied on this. However, no init scripts are shipped for BSD. Those would need to be modified by the user. For older versions they can use the --daemonize command line option. For versions which have dropped daemonize support it is recommended to use a separate tool to daemonize.
On systemd based deployments this option already had no effect since the service file included the --no-daemonize option. The config was misleading there.
> Refs #31118 - Remove daemon option from settings.yaml

- manifests/plugin/salt.pp
Refers to this ticket: [#35396](https://projects.theforeman.org/issues/35396).
An error is thrown when reading the configuration file, since the saltuser (different from _root_) must read the config file. Therefore, the file permission is set to _readable_ for _others_.
> Fixes #35396 - allow non-root user to read Salt master config file

- manifests/module.pp
- manifests/module/bmc.pp
- manifests/module/dhcp.pp
- manifests/module/dns.pp
- manifests/module/tftp.pp
- spec/defines/foreman_proxy_module_spec.rb
foreman_proxy::plugin::module uses $title.capitalize() and now foreman::module does too. This makes it more consistent. It also explicitly sets the feature where needed. This was explained in an issue[1].
[1]: https://github.com/theforeman/puppet-foreman_proxy/pull/773#issuecomment-1206289813
> Change module feature default to capitalize

- manifests/plugin/ansible.pp
- spec/classes/foreman_proxy__plugin__ansible_spec.rb
sp_ansible depends on sp_rex to work, but we never properly setup the later unless the user *explicitly* also asks for it
> Fixes #35809 - always enable rex when enabling ansible

- manifests/plugin/ansible/params.pp
- spec/classes/foreman_proxy__plugin__ansible_spec.rb
To properly detect if the remote end just disappears
Ansible counterpart of https://github.com/theforeman/smart_proxy_remote_execution_ssh/pull/100
> Fixes #35925 - Enable ssh server keepalive for ansible

- manifests/tftp/netboot.pp
this was done on Debian-family systems already, but not on RedHat, resulting in "double" errors if the package could not be installed:
/Stage[main]/Foreman_proxy::Tftp::Netboot/Package[grub2-efi-x64]/ensure: change from 'purged' to 'present' failed: Execution of '/bin/dnf -d 0 -e 1 -y install grub2-efi-x64' returned 1: Error: Unable to find a match: grub2-efi-x64
/Stage[main]/Foreman_proxy::Tftp::Netboot/File[/var/lib/tftpboot/grub2/grubx64.efi]: Could not evaluate: Could not retrieve information from environment production source(s) file:///boot/efi/EFI/redhat/grubx64.efi
> require the grub packages before copying files on RedHat too

- .fixtures.yml
We require Puppet 6 anyway, so this will always be true. Also simplifies the mosquitto to be a simple string.
> Remove Puppet 6+ conditionals in fixtures

- manifests/tftp/netboot.pp
Remains backwards-compatible with supported distros, and we don't have to look for openeuler or oraclelinux or any other EL variant.
> Simplify grub_efi_path on redhat family

- manifests/plugin/salt.pp
Fixes 4ea5cf8aa5be61ed49bcacef0479ab6674e840ae
> Set group owner to foreman-proxy for Salt config

- spec/setup_acceptance_node.pp
This hasn't been needed since we can depend on ansible-core.
> Stop installing centos-release-ansible-29 in CI

- manifests/tftp/netboot.pp
Apparently they didn't get the memo when rebranding their distro.
> Make exception to grub_efi_path for OracleLinux

- examples/salt.pp
- spec/acceptance/salt_spec.rb
I wrote this to test out https://github.com/theforeman/puppet-foreman_proxy/pull/826 and this makes the future easier.
While testing I noticed there's a file placed by the plugin:
```console
rubygem-smart_proxy_salt-5.0.1-1.fm3_9.el8.noarch
```
I do not know who uses this file, but the installer doesn't manage the content so I question its use.
> Add acceptance tests for salt plugin

- manifests/plugin/dynflow.pp
- spec/classes/foreman_proxy__plugin__dynflow_spec.rb
This was deprecated in the latest release and will be dropped in the future.
The systemd dependency is a soft dependency. The lower bound is now version 4.0.0
> Move away from systemd::service_limits

- .fixtures.yml
- README.md
- manifests/plugin/container_gateway.pp
- spec/acceptance/container_gateway_spec.rb
- spec/classes/foreman_proxy__plugin__container_gateway_spec.rb
- templates/plugin/container_gateway.yml.erb
Draft PR for adding postgres support to the container gateway class. Settings should match the in-progress new settings here: https://github.com/Katello/smart_proxy_container_gateway/pull/33/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R42-R47
I'm not certain that this is the right direction for adding postgres support -- so far I'm thinking that the actual database should be create in puppet-foreman_proxy_content so I don't add a hard postgres library requirement to puppet-foreman_proxy.
foreman_proxy_content PR: https://github.com/theforeman/puppet-foreman_proxy_content/pull/479
Another question was about testing the random database password -- is there a way to stub the `extlib::random_password(32)` call?
> Fixes #37325 - make postgres the container gateway default DB

- metadata.json
Added AlmaLinux  9 to the supported operating systems in metadata.json.
These changes ensure that we start testing with AlmaLinux 8 and 9 instead of CentOS 8 Stream. This update is part of our transition to better support AlmaLinux in our Puppet modules.
See, for details: https://github.com/theforeman/foreman-infra/issues/2087
> Add AlmaLinux 9 support

- manifests/module.pp
- manifests/plugin/container_gateway.pp
- manifests/plugin/module.pp
- spec/acceptance/container_gateway_spec.rb
- spec/classes/foreman_proxy__plugin__container_gateway_spec.rb
- spec/defines/foreman_proxy_module_spec.rb
- spec/defines/foreman_proxy_plugin_module_spec.rb
- spec/defines/foreman_proxy_settings_file_spec.rb
This implements support to ensure container_gateway is disabled or absent. It does not remove the database, so it's easy to install again and pick up where you left.
> Refs #37707 - Support purging container_gateway

- manifests/plugin/ansible/params.pp
- spec/classes/foreman_proxy__plugin__ansible_spec.rb
Previously, we added a hardcoded `ProxyCommand=none` because ipa-client-install added
`ProxyCommand /usr/bin/sss_ssh_knownhostsproxy -p %p %h` into `/etc/ssh/ssh_config`, which caused failure to execute ansible commands on systems without the `/sbin/nologin` shell. [^1] However; this also prevents users from using their own jump host in the ssh configuration since the hardcoded command line arguments always take precedence.
Since this issue was fixed in the ipa tooling 3 years ago (they now use the `Match exec true` rule)[^2], I propose we remove the hardcoded ProxyCommand to allow users to specify their own jump hosts. The same is being done for remote execution. [^3]
Some users who have configured the ipa client before the fix landed in ipa might still report that they are getting …
> Fixes #37803 - Remove hardcoded ProxyCommand

- manifests/init.pp
- manifests/params.pp
This enables user to run foreman-proxy on a Puppet Enterprise primary.
> Add support for running on Puppet Enterprise Primary

- manifests/tftp.pp
A new parameter 'bootloader_universe' has been added for tftp on the Smart Proxy side for the new "Grub2 UEFI SecureBoot (target OS)" PXE loader. This PR aims to add the new parameter to foreman-installer.
Refer to https://github.com/theforeman/smart-proxy/pull/877 and https://github.com/theforeman/foreman/pull/9864 for more information.
> Fixes #36940 - Add SecureBoot support for arbitrary operating systems to "Grub2 UEFI" PXE loaders

- manifests/register.pp
In case there runs puppetserver on the same node *and* foreman is used as an ENC, the registration needs to happen before the smart proxy is configured, otherwise the ENC script cannot authenticate itself to foreman.
> Ensure proxy register runs before puppetserver service

- metadata.json
- spec/classes/foreman_proxy__plugin__ansible_spec.rb
Foreman 3.13 doesn't provide packages anymore for those platforms.
> Drop EoL EL8 / Ubuntu 20.04 / Debian 11 support

- manifests/plugin/omaha.pp
- manifests/plugin/pulp.pp
Since puppet-lint 4.3.0 this is checked.
> Fix space_before_arrow lint check

- manifests/plugin/remote_execution/mosquitto.pp
- spec/classes/foreman_proxy__plugin__remote_execution__mosquitto_spec.rb
The default built in ciphers can be less secure. On Red Hat there is the special cipher that's PROFILE=SYSTEM where OpenSSL will respect what's configured in crypto-policies. This keeps the configuration out of the installer while still giving the user control. Out of the box this is also more secure.
I don't know how to test this. When I tried `openssl s_client -connect localhost:1883` it disconnects me. Same with `sslscan --show-ciphers localhost:1883`. @adamruzicka any idea?
> Fixes #38279 - Respect crypto-policies in mosquitto on EL

- .fixtures.yml
Since we pull the main branch for testing, and it was updated to drop Puppet 7 support Debian and Ubuntu testing fails:
https://github.com/puppetlabs/puppetlabs-apt/commit/3f9afe6a4840a5804a740d924f6fde0b277db8e0
> Pin puppet-apt since it dropped Puppet 7
