spec/classes/foreman_proxy__config__spec.rb
templates/settings.yml.erb

Need this for various plugins.

Fixes #7833 - foreman_url is set for the smart proxy

---

manifests/config.pp
manifests/init.pp
manifests/params.pp
spec/classes/foreman_proxy__config__spec.rb
templates/templates.yml.erb

Really, http://projects.theforeman.org/issues/8990 would be nice for this as well, but not sure I'll have time to take care of that one.

Configure templates module

---

metadata.json

Should allow librarian to resolve deps: http://ci.theforeman.org/job/packaging_trigger_installer_develop/233/console

Compatible with puppet-puppet 3.0.0

---

manifests/params.pp
metadata.json

needed after theforeman/puppet-puppet#241 got merged

update (server_)vardir parameter from puppet-puppet

---

manifests/params.pp
spec/classes/foreman_proxy__config__spec.rb
templates/tftp.yml.erb

More than one user has come by with this problem recently

fixes #9896 -  don't set tftp_servername by default

---

manifests/config.pp
manifests/init.pp
manifests/params.pp
spec/classes/foreman_proxy__config__spec.rb
spec/lib/module_spec_helper.rb
templates/puppet.yml.erb

Closes GH-168
Also updates the tests a bit.

Add puppet_use_cache parameters

---

manifests/plugin/salt.pp
manifests/plugin/salt/params.pp
spec/classes/foreman_proxy__plugin__salt_spec.rb
templates/plugin/salt.yml.erb

Needs https://github.com/theforeman/foreman_salt/pull/35 first

refs #8473 - configure salt API in salt.yml

---

.fixtures.yml
metadata.json

I'd suggest we bump the version in the other two repos next, and consider making major releases.

pl-concat related fixes

---

manifests/init.pp
manifests/params.pp
spec/classes/foreman_proxy__config__spec.rb
templates/dhcp.yml.erb
templates/puppet.yml.erb
templates/settings.yml.erb

Some new parameters that were added to the smart proxy between 1.8 and 1.9.  The only I haven't done yet is https://github.com/theforeman/smart-proxy/commit/75f587114cee27f084839f7e0d2cde013b986b7f, which probably needs more work due to sudoers rules.

Add new parameters

---

manifests/config.pp
manifests/params.pp
manifests/plugin/chef/params.pp
manifests/plugin/salt/params.pp
manifests/settings_file.pp
spec/classes/foreman_proxy__config__spec.rb
spec/classes/foreman_proxy__plugin__chef__spec.rb
spec/classes/foreman_proxy__plugin__openscap_spec.rb
templates/settings.yml.erb

This would bring in #184, except the FreeBSD parts in params.pp. Updated tests are still missing there, so I'd like to bring this in early to minimize diffs when other changes go in.

prepare support for more OSes & refactor few tests

---

manifests/params.pp
metadata.json
spec/classes/foreman_proxy__config__spec.rb
spec/classes/foreman_proxy__proxydns__spec.rb

Opening this mainly for comments, tests are not yet adjusted.
I'm unsure if it's better to have all the information per osfamily in params.pp or only the differing variables but did it the first way as this is easier for me at the moment.

add FreeBSD support

---

manifests/plugin/discovery.pp
manifests/plugin/discovery/params.pp
spec/classes/foreman_proxy__plugin__discovery_spec.rb
templates/settings.yml.erb

Perhaps installing the discovery image should be optional? Here's an initial PR without it.

add support for discovery plugin

---

manifests/init.pp
manifests/params.pp
manifests/register.pp
spec/classes/foreman_proxy__register__spec.rb

make real_registered_proxy_url take the correct port

make real_registered_proxy_url take the correct port

---

manifests/install.pp
metadata.json

to be merged after theforeman/puppet-foreman#404

use moved foreman::repos define

---

manifests/params.pp
spec/classes/foreman_proxy__config__spec.rb

will be needed after theforeman/foreman#3331 is merged for it to work

copy mboot.c32 for tftp proxies

---

.fixtures.yml

Should fix the test failures on master.

Add puppetlabs-apt to test fixtures for puppet-foreman changes

---

manifests/init.pp
manifests/params.pp
manifests/proxydhcp.pp
spec/classes/foreman_proxy__proxydhcp__spec.rb

I added a dhcp_search_domains parameter. I didn't write any tests because I don't know how.

add dhcp_search_domains parameter

---

manifests/init.pp
manifests/params.pp
manifests/tftp.pp
spec/classes/foreman_proxy__config__spec.rb

with this I can use -installer also with libvirt (which brings its own tftp server, but I still want the syslinux files to get copied)

add tftp_managed parameter

---

metadata.json

Permit theforeman/puppet 6.x

---

manifests/plugin/dns/powerdns.pp
manifests/plugin/dns/powerdns/params.pp
spec/classes/foreman_proxy__plugin__dns__powerdns_spec.rb
templates/plugin/dns_powerdns.yml.erb

Add dns::powerdns options

---

manifests/tftp.pp
spec/classes/foreman_proxy__config__spec.rb

Another fix for #289 to try to push this along and get it into a release since this is a blocking issue. I've taken the original PR from @brandonweeks and added a commit with tests. If you'd prefer they were all squashed into a single commit of my own, I am happy to do that too.

 Closes GH-289: Add tests for EL6 EFI 

---

metadata.json

Permit new theforeman/* module versions

---

manifests/params.pp
metadata.json
spec/classes/foreman_proxy__config__spec.rb
spec/classes/foreman_proxy__plugin__discovery_spec.rb
spec/classes/foreman_proxy__proxydns__spec.rb
spec/defines/foreman_proxy_plugin_spec.rb

Tested locally, seems to work for me.

Add Archlinux support

---

manifests/params.pp

refactor puppetssh_command default

---

CHANGELOG.md

Prepare 5.0.0 changelog

---

.fixtures.yml
metadata.json

Allow extlib version 1.x

---

manifests/plugin/remote_execution/ssh.pp
manifests/plugin/remote_execution/ssh/params.pp
spec/classes/foreman_proxy__plugin__remote_execution__ssh_spec.rb

Before I spend time on adding test, I'd like to get opinions whether this is acceptable. The option might also default to false.

Fixes #18215 - Install REX SSH key

---

spec/classes/foreman_proxy__config__spec.rb
templates/dns_nsupdate.yml.erb

Make nsupdate dns_key optional

---

manifests/tftp.pp
spec/classes/foreman_proxy__tftp_spec.rb

see puppetlabs/puppetlabs-stdlib#716 (MODULES-4377)

fix tests after ensure_packages changed

---

CHANGELOG.md

add changelog for 6.0.0

---

manifests/init.pp
manifests/params.pp
manifests/proxydhcp.pp
spec/classes/foreman_proxy__proxydhcp__spec.rb

@ekohl based on our discussions, @lzap you may also want to check

Fixes #20683 - Set ACLs on dhcp

---

manifests/tftp.pp

Backport of https://github.com/theforeman/puppet-foreman_proxy/pull/374.

Refs #21006 - Workaround broken grub2 on EL7.4

---

manifests/tftp.pp

tft_root is undefined, http://ci.theforeman.org/job/systest_foreman/13770/tapResults/

Fix typo tft_root -> tftp_root

---

CHANGELOG.md

add 6.0.3 changelog

---

manifests/init.pp
manifests/params.pp
spec/classes/foreman_proxy__config__spec.rb
templates/settings.yml.erb

Needs https://github.com/theforeman/smart-proxy/pull/559

refs #21350 - installer support for disable_tls_versions

---

manifests/plugin/openscap.pp
manifests/plugin/openscap/params.pp
spec/classes/foreman_proxy__plugin__openscap_spec.rb

Submitted as a separate PR for easy changelogs.
Closes GH-373

Remove the configure_openscap_repo parameter

---

metadata.json

puppet-foreman will get a major bump
https://github.com/theforeman/puppet-tftp/pull/69 is also a major

Allow foreman 9.x and tftp 4.x

---

spec/classes/foreman_proxy__plugin__dynflow_spec.rb
spec/classes/foreman_proxy__plugin__pulp_spec.rb

Update spec tests

---

manifests/plugin/remote_execution/ssh.pp
manifests/plugin/remote_execution/ssh/params.pp
spec/classes/foreman_proxy__plugin__dynflow_spec.rb
spec/classes/foreman_proxy__plugin__remote_execution__ssh_spec.rb
templates/plugin/remote_execution_ssh.yml.erb

Test failures are unrelated, on master it was still failing

Fixes #22862 - add async_ssh param

---

manifests/plugin/ansible.pp
spec/classes/foreman_proxy__plugin__ansible_spec.rb
templates/plugin/ansible.cfg.erb

This PR is here to test the functionality works.

Configure ansible reporting callback

---

files/grub.cfg

This is just to make things more clear and also this changes the regexp to more
tested version which is in our community-templates repo (covered by RH QA).

Updated grub.cfg with explanation

---

manifests/install.pp
spec/acceptance/basic_spec.rb

I am trying to find a place where to put spec for this but I am lost in this spec codebase. Help.

Install foreman-proxy-journald when JOURNALD is set

---

spec/classes/foreman_proxy__config__spec.rb
templates/bmc.yml.erb

This also matches the template closer to the example file

Refs #25825 - Add tests around BMC SSH parameters

---

manifests/params.pp

Remove comment about a removed parameter for the $custom_repo parameter but that's been removed. Also simplifies puppet handling in params.pp.

Clean up params.pp

---

manifests/plugin/pulp.pp
manifests/plugin/pulp/params.pp
spec/classes/foreman_proxy__plugin__pulp_spec.rb
templates/plugin/pulp3.yml.erb

Since smart_proxy_pulp 1.4.0 pulp3.yml is created.

Add pulp3 options to the pulp plugin

---

manifests/plugin/pulp.pp
manifests/plugin/pulp/params.pp
spec/classes/foreman_proxy__plugin__pulp_spec.rb
templates/plugin/pulp3.yml.erb
templates/plugin/pulpcore.yml.erb

fixes https://github.com/theforeman/puppet-foreman_proxy/issues/550

use pulpcore naming convention

---

spec/classes/foreman_proxy__plugin__chef__spec.rb
templates/plugin/chef.yml.erb

This uses the correct variable which means it'll only listen on HTTPS as intended.

Fix chef plugin listen on

---

manifests/plugin/pulp.pp
manifests/plugin/remote_execution/ssh.pp

Note I haven't verified this actually works because you need a full Katello and REX setup.

Declare features on SSH and Pulp modules

---

metadata.json

correct needed foreman dependency

---

files/grub.cfg

Small changes to comments, which I hope will improve readability of this file

Improve the readability of the provided grub.cfg

---

examples/httpboot.pp
manifests/proxydhcp.pp
spec/acceptance/httpboot_spec.rb
templates/httpboot_dhcp_class.erb

Related discussion: https://community.theforeman.org/t/puppet-update-for-dhcpd-conf-and-http-boot/19981

Set up HTTPClients in DHCP

---

.github/workflows/acceptance.yml
.github/workflows/cron.yml
.sync.yml
Gemfile

2d88948b649402fd990959cd141192629a362f1f missed these parts.

Complete Github Actions migration

---

.fixtures.yml
examples/ansible.pp
manifests/plugin/ansible/runner.pp
spec/acceptance/ansible_spec.rb
spec/classes/foreman_proxy__plugin__ansible_spec.rb
spec/setup_acceptance_node.pp

(cherry picked from commit af2656f8ff58626c0f907d06e33856d36ee663f6)

Fixes #31430 - use correct key and server for ansible-runner deb

---

manifests/plugin/ansible.pp
manifests/plugin/ansible/params.pp
manifests/plugin/ansible/runner.pp
spec/acceptance/ansible_spec.rb
spec/classes/foreman_proxy__plugin__ansible_spec.rb

don't manage runner repo on Debian

---

CHANGELOG.md
metadata.json

I believe this should wait for #666 and #667 to be merged first. @evgeni could you please confirm?

Release 18.1.0

---

manifests/plugin/dynflow.pp
spec/classes/foreman_proxy__plugin__dynflow_spec.rb

(cherry picked from commit 763aba8f18e028548152d8a41bbafc142702c5e8)

Fixes #32078 - explicitly notify dynflow core service on changes

---

CHANGELOG.md

Release 19.0.0

---

manifests/tftp.pp
metadata.json

Announcement of "Enhancement" see here: https://puppet.com/docs/puppet/6/release_notes_puppet.html#enhancements_puppet_x_23_0-PUP-10946

Fixes #33688 - Set max_files to unlimited for TFTP directories

---

CHANGELOG.md

Release 20.0.0

---

metadata.json

There is one breaking change already present and another on the way so I figure we ought to just bump the version ahead of time to reflect this.

Bump master to 22.0.0

---

CHANGELOG.md

Release 22.0.0

---

CHANGELOG.md
metadata.json

these need to go in:
- https://github.com/theforeman/puppet-foreman_proxy/pull/750
- https://github.com/voxpupuli/puppet-mosquitto/pull/25

Release 22.1.0

---

metadata.json

add missing dep on puppet/mosquitto

---

README.md
manifests/params.pp
metadata.json
spec/acceptance/journald_spec.rb
spec/defines/foreman_proxy_plugin_spec.rb
spec/spec_helper_acceptance.rb
spec/support/plugin.rb

Drop EL7 support

---

manifests/plugin/ansible/params.pp

Refs 7f6601fcf0aa2b776429e7cabe0a0ad7cf038ddb
I missed this in the original commit.

Remove manage_runner_repo defaults from params.pp

---

spec/classes/foreman_proxy__spec.rb
templates/bmc.yml.erb
templates/dhcp_isc.yml.erb
templates/dns.yml.erb
templates/logs.yml.erb
templates/puppet.yml.erb
templates/puppet_proxy_puppet_api.yml.erb
templates/puppetca.yml.erb
templates/puppetca_token_whitelisting.yml.erb
templates/realm.yml.erb
templates/realm_freeipa.yml.erb
templates/registration.yml.erb
templates/settings.yml.erb
templates/tftp.yml.erb

This keeps the diff minimal compared to what's packaged in the RPMs/debs and that means it's easier to see what really changed on the first run.

Bring config files closer to packaged versions

---

manifests/init.pp
manifests/proxydns.pp
metadata.json

Goes with https://github.com/theforeman/puppet-dns/pull/264.

Refs #37604 - Validate DNS forwarders values

---

manifests/plugin/ansible/runner.pp
spec/classes/foreman_proxy__plugin__ansible_spec.rb

we stopped using it a long time ago, and had it on "absent" for a while.

stop removing ansible runner yumrepo

---

CHANGELOG.md
metadata.json

Needs https://github.com/theforeman/puppet-foreman_proxy/pull/855

Release 28.0.0

---

manifests/proxydhcp.pp
spec/classes/foreman_proxy__proxydhcp__spec.rb

Fixes: f8fb58e2ca06 ("Fixes #30632 - Set up HTTPClients in DHCP")

Fixes #38259 - Use the correct ssl_port variable

---

manifests/plugin/container_gateway.pp
spec/classes/foreman_proxy__plugin__container_gateway_spec.rb
templates/plugin/container_gateway.yml.erb

This supports https://github.com/Katello/smart_proxy_container_gateway/pull/46

Add client_endpoint support to container_gateway plugin
